"""add characteristic

Revision ID: 17a8f3a63e28
Revises: ef8b600c760d
Create Date: 2025-03-02 10:07:40.594451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a8f3a63e28'
down_revision: Union[str, None] = 'ef8b600c760d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Themes', sa.Column('characteristic', sa.Text()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Themes', 'characteristic')
    # ### end Alembic commands ###
