"""for prompt

Revision ID: 6558e5226370
Revises: b66791b81612
Create Date: 2025-03-05 13:41:23.962722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6558e5226370'
down_revision: Union[str, None] = 'b66791b81612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.String(length=50), nullable=False),
    sa.Column('characteristic', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Themes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Themes',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name_theme', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('characteristic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Themes_pkey')
    )
    op.drop_table('Users')
    # ### end Alembic commands ###
