"""add characteristic

Revision ID: 7314573cf864
Revises: e83eb154f7d5
Create Date: 2025-03-01 21:01:46.700517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7314573cf864'
down_revision: Union[str, None] = 'e83eb154f7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Themes', sa.Column('characteristic', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Themes', 'characteristic')
    # ### end Alembic commands ###
