"""add characteristic

Revision ID: 733a766a6982
Revises: 7fabeb2a9fbf
Create Date: 2025-03-02 09:52:04.089996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733a766a6982'
down_revision: Union[str, None] = '7fabeb2a9fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Themes', sa.Column('characteristic', sa.Text()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Themes', 'characteristic')
    # ### end Alembic commands ###
