"""Initial revision

Revision ID: b66791b81612
Revises: 
Create Date: 2025-03-02 10:17:50.188132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66791b81612'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Themes',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('assistant_id', sa.String(length=50), nullable=False),
    sa.Column('thread_id', sa.String(length=50), nullable=False),
    sa.Column('name_theme', sa.String(length=50), nullable=False),
    sa.Column('characteristic', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Themes')
    # ### end Alembic commands ###
