"""arguments_values_human

Revision ID: c5ddde981b78
Revises: c6f9ce84408a
Create Date: 2025-03-10 23:07:05.663993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ddde981b78'
down_revision: Union[str, None] = 'c6f9ce84408a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('values_human', sa.Text(), nullable=False))
    op.drop_column('Users', 'unit')
    op.drop_column('Users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('Users', 'values_human')
    # ### end Alembic commands ###
