"""Initial revision

Revision ID: ef8b600c760d
Revises: 
Create Date: 2025-03-02 10:07:10.100190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8b600c760d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Themes', 'characteristic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Themes', sa.Column('characteristic', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
