services:
  bot:
    build: .
    command: alembic upgrade head && python main.py
    env_file:
      - .env
    volumes:
      - .:/bot
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - deploy_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/posgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    networks:
      - deploy_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - deploy_network

volumes:
  postgres_data:
  redis_data:

networks:
  deploy_network:
    driver: bridge